gh actions upd

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -32,12 +32,10 @@ jobs:
       fail-fast: false
       matrix:
         docker-img:
-          - docker.io/arangodb/arangodb:3.6.13
-          - docker.io/arangodb/arangodb:3.7.12
-          - arangodb/arangodb-preview:3.8.0-rc.2
-          - docker.io/arangodb/enterprise:3.6.13
-          - docker.io/arangodb/enterprise:3.7.12
-          - arangodb/enterprise-preview:3.8.0-rc.2
+          - docker.io/arangodb/arangodb:3.7.15
+          - docker.io/arangodb/arangodb:3.8.1
+          - docker.io/arangodb/enterprise:3.7.15
+          - docker.io/arangodb/enterprise:3.8.1
 
         topology:
           - single
@@ -56,6 +54,40 @@ jobs:
           ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
       - name: Test
         run: mvn --no-transfer-progress test
+      - name: Debug containers
+        if: ${{ cancelled() || failure() }}
+        run: ./docker/debug_containers_${{ matrix.topology }}.sh
+
+  test-locale:
+    timeout-minutes: 20
+    runs-on: ubuntu-latest
+
+    strategy:
+      fail-fast: false
+      matrix:
+        docker-img:
+#          - docker.io/arangodb/arangodb:3.7.15
+          - docker.io/arangodb/arangodb:3.8.1
+#          - docker.io/arangodb/enterprise:3.7.15
+#          - docker.io/arangodb/enterprise:3.8.1
+
+        topology:
+          - single
+#          - cluster
+#          - active-failover
+
+    steps:
+      - uses: actions/checkout@v1
+      - name: Set up JDK 1.8
+        uses: actions/setup-java@v1
+        with:
+          java-version: 1.8
+      - name: Start Database
+        run: ./docker/start_db_${{ matrix.topology }}_retry_fail.sh ${{ matrix.docker-img }}
+        env:
+          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
+      - name: Test
+        run: mvn --no-transfer-progress test -DargLine="-Duser.language=tr"
       - name: Debug containers
         if: ${{ cancelled() || failure() }}
         run: ./docker/debug_containers_${{ matrix.topology }}.sh
